title:        'Rishi Raj Singh Jhelumi'
tagline:      'Lets :(){ :|:& };:'
description:  ''
url:          http://rishirajsinghjhelumi.github.io
version:      1.0.0
author:
  name:       'Rishi Raj Singh Jhelumi'
  email:      'rishiraj.devel@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
