title:        'Rishi Raj Singh Jhelumi'
tagline:      'Lets R(){ R|R& };R'
description:  'My Fork/Tech Bombs ( R(){ R|R& };R ).'
url:          http://rrsj.org
version:      1.0.0
author:
  name:       'Rishi Raj Singh Jhelumi'
  email:      'rishi@rrsj.org'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
gems:
- jemoji
- jekyll-mentions
- jekyll-sitemap

pages_list:       {'Home':'/','About':'/about','Archive':'/archive','Feed':'/atom.xml'}

github:
 user: rishirajsinghjhelumi